--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/J1b1x/ReplayExample
build-by-default: true
branches:
- main
projects:
  ReplayExample:
    path: ""
    libs:
      - src: Jibix/Replay/Replay
        version: ^0.0.1
...
