--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/J1b1x/ReplayExample
build-by-default: true
branches:
- main
projects:
  ReplayExample:
    path: ""
    libs:
      - src: J1b1x/Replay/Replay
        version: ^0.0.1
      - src: J1b1x/AsyncMedoo/AsyncMedoo
        version: ^0.0.1
      - src: J1b1x/Forms/Forms
        version: ^1.0
      - src: J1b1x/FunctionalItem/FunctionalItem
        version: ^0.0.1
...
