name: "Replay"
version: 1.0
api: 5.0.0
author: "Jibix"
main: Jibix\ReplayExample\Main
permissions:
  replay.command:
    default: op
  replay.command.record:
    default: op
  replay.command.stop:
    default: op
  replay.command.world:
    default: op
  replay.search:
    default: op
  replay.delete:
    default: op