name: "GameReplay"
version: 1.0.3
api: 5.3.0
author: "Jibix"
main: Jibix\ReplayExample\Main
permissions:
  gamereplay.command:
    default: op
  gamereplay.command.record:
    default: op
  gamereplay.command.stop:
    default: op
  gamereplay.command.world:
    default: op
  gamereplay.search:
    default: op
  gamereplay.delete:
    default: op
